#! /bin/sh

# Copyright 2019 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### BEGIN INIT INFO
# Provides:          dvbcsstv-proxy
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to launch dvbcsstv proxy server
# Description:       A pyhton-based proxy server for various DVB-CSS protocols requiring UDP
### END INIT INFO

# Source the init functions (required by dpkg build)
. /lib/lsb/init-functions

PID_FILE=/var/run/dvbcsstv-proxy.pid

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting dvbcsstv-proxy service"
    cd /usr/lib/2immerse-firmware/server-tvemu
    /usr/bin/python node_modules/.bin/dvbcsstv-proxy-server.py > /var/log/dvbcsstv-proxy.log 2>&1 &
    echo $! > $PID_FILE
    ;;
  stop)
    echo "Stopping dvbcsstv-proxy service"
    if [ -f $PID_FILE ]; then
        pkill -F $PID_FILE
        rm -f $PID_FILE
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/dvbcsstv-proxy {start|stop}"
    exit 1
    ;;
esac

exit 0
