#!/bin/sh

# Copyright 2019 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ "$1" = "configure" ]; then

  # Activate 2immerse-firmware's nginx configuration
  if [ -d /etc/nginx/sites-enabled -a ! -e /etc/nginx/sites-enabled/captive-portal.conf -a -e /etc/nginx/sites-available/captive-portal.conf ]; then
    # Enable new nginx site
    ln -sf /etc/nginx/sites-available/captive-portal.conf /etc/nginx/sites-enabled/captive-portal.conf
  fi
  if [ -d /etc/nginx/sites-enabled -a -e /etc/nginx/sites-enabled/default ]; then
    # remove symbolic link to default server configuration to disable it
    rm -fr /etc/nginx/sites-enabled/default
  fi

  # Required by dvbcsstv-proxy-server
  pip install --no-index --find-links /usr/lib/2immerse-firmware/pypi 'pydvbcss==0.4.1'

  # Install certs used for https connections to local services
  # 2immerseCA.pem is installed in /usr/share/ca-certificates
  update-ca-certificates
  
  # Stop the systemd-resolved DNS resolver so it doesn't conflict with dnsmasq
  systemctl stop systemd-resolved || true
  systemctl disable systemd-resolved || true

  # Configure to run at startup
  update-rc.d dvbcsstv-proxy defaults || true
  update-rc.d app2app-dial-server defaults || true
  systemctl enable dnsmasq-ap || true
  systemctl enable 2immerse-firmware || true
  systemctl enable chromium-remote-debug || true
  systemctl enable kiosk || true
fi
