#!/bin/sh

# Copyright 2019 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/doc/parted ]; then

  update-rc.d -f app2app-dial-server remove || true
  update-rc.d -f dvbcsstv-proxy remove || true
  systemctl disable dnsmasq-ap || true
  systemctl disable 2immerse-firmware || true
  systemctl disable chromium-remote-debug || true 
  systemctl disable kiosk || true 

  # Re-enable systemd-resolved DNS resolver
  systemctl enable systemd-resolved || true
  systemctl start systemd-resolved || true

  # Clear out custom certificate once the package has been uninstalled.
  update-ca-certificates
fi

